### ISSUE TITLE
Add the package in radare2 package manager repository

### ISSUE THREAD

**Issue by XVilka** [chase1635321/r2angr#1]
To improve visibility and ease of installation for radare2 and Cutter users it would be nice to add the project as a package in `r2pm`, see the repository here https://github.com/radareorg/radare2-pm.

Note, that there is ongoing work on the new cross-platform package manager written in Go here: https://github.com/radareorg/r2pm/
In the future we will switch to this format, allowing binary packages as well. But currently, only source-level installations are possible.

**Comment by chase1635321** [comment]
Registering a core plugin seems to be causing a segfault. Running `r2 -i plugin.py -` works fine, but putting `plugin.py` in the `radare2/plugins/` folder causes radare2 to segfault on start. An example plugin is below.

```
#! /usr/bin/env python3
# Copyright (C) 2017 Chase Kanipe

"""
import r2lang
import sys

def modality(_):
    def process(command):
        if not command.startswith("M"):
            print("Running command...")
            return 0
        return 1

    return {"name": "modality",
            "licence": "GPLv3",
            "desc": "Integrates angr with radare2",
            "call": process}

# Register the plugin
if not r2lang.plugin("core", modality):
    print("An error occurred while registering modality")
```

I'm new to r2pm, is this an radare2 bug or am I registering/implementing the plugin incorrectly?

**Comment by 0xchase** [comment]
Added [pull request](https://github.com/radareorg/radare2-pm/pull/106)
